#ifndef HYPERTRIE_H
#define HYPERTRIE_H

#pragma once

/* Auto-generated by cbindgen. Do not edit manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace hypertrie {

struct HyperTrie;

extern "C" {

HyperTrie *hypertrie_new();

/// # Safety
/// `ptr` must be a valid pointer returned by `hypertrie_new` and not yet freed.
void hypertrie_free(HyperTrie *ptr);

/// # Safety
/// `ptr` must be a valid pointer returned by `hypertrie_new` and not yet freed.
void hypertrie_insert(const HyperTrie *ptr, uint32_t s, uint32_t p, uint32_t o);

/// # Safety
/// `ptr` must be a valid pointer returned by `hypertrie_new` and not yet freed.
bool hypertrie_search(const HyperTrie *ptr, uint32_t s, uint32_t p, uint32_t o);

}  // extern "C"

}  // namespace hypertrie

#endif  // HYPERTRIE_H
